version: '2.1'

services:
  db:
    container_name: db
    image: mysql:8
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: roor
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672