spring:
  data:
    mongodb:
      uri: mongodb://192.168.99.100:27017/test

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instanceId: db-reactive-stock-sandbox
