server:
  port: 0

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/test

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
