server:
  port: 0

spring:
  data:
    mongodb:
      uri: mongodb://192.168.99.100:27017/test

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 30