server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://db:3306/test
    username: root
    password: root
    dbcp2:
      test-while-idle: true
    validation-query: select 1
  jpa:
    hibernate:
      ddl-auto: update
    naming:
      strategy: org.hibernate.cfg.ImprovedNamingStrategy

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
